# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provision "install jdk", type: "shell", inline: "sudo apt install -y openjdk-11-jdk"
end
