# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provision "nettools", type: "shell" do | prov |
    prov.inline = "sudo apt update -y && sudo apt install -y net-tools"
  end
end
