# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do | vbconfig, vboverride  |
    vboverride.vm.box = "hashicorp/precise64"
    vboverride.vm.network "private_network", type: "dhcp"
  end

  config.vm.provider "hyperv" do | hyperv |
    hyperv.vm.network "public_network", type: "dhcp"
  end
end
