# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do | vb |
    vb.cpus = 4
    vb.memory = 1024
    vb.name = "pcustomize"
    vb.gui = true
    vb.customize ["modifyvm", :id, "--vram", "256"]
  end
end
