# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provision "installtree", type:"shell" do | prov | 
    prov.path = "installpkg.sh"
    prov.args = "tree"
  end
  config.vm.provision "installnettools", type: "shell" do | prov |
    prov.path="installpkg.sh"
    prov.args = "net-tools"
  end
end
