# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "techsriman/ubuntu-20.04-3"
  config.vm.provider "virtualbox" do | vb |
    vb.gui = true
    vb.name="ubuntu20.04-3"
  end
end
