# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  $script = <<-SCRIPT
    R=$(shuf -i 100-2000 -n 1)
    echo $R > /home/vagrant/random.txt
  SCRIPT
  $script2 = <<-SCRIPT
    R1=$(shuf -i 2000-3000 -n 1)
    echo $R1 > /home/vagrant/random2.txt
  SCRIPT
  config.vm.provision "random", type: "shell", inline: $script, run: "always"
  config.vm.provision "randomno", type: "shell", inline: $script2, run: "once"
  config.vm.provision "installtree", type: "shell", inline: "sudo apt install -y tree", run: "never"
end
