# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provision "data", type: "file", source: "data.csv", destination: "/home/vagrant/"  
end
